---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: true
  base_model: \LazyRecord\BaseModel
  base_collection: \LazyRecord\BaseCollection
  paths:
    - tests
cache:
  class: LazyRecord\Cache\Memcache
  servers:
    - { host: localhost, port: 11211 }
data_sources:
  default:
    # dsn: 'pgsql:dbname=lazy_test'
    # dsn: 'sqlite:tests.db'
    dsn: 'sqlite::memory:'
    query_options: { quote_column: true, quote_table: true }
  mysql:
    dsn: 'mysql:host=localhost;dbname=testing'
    user: testing
    pass: testing
# create database testing charset utf8;
# grant all privileges on testing.* to testing@localhost identified by 'testing';
  pgsql:
    dsn: 'pgsql:host=localhost;dbname=testing'
    user: testing
    pass: testing
