---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: 1
# Customize your schema class loader
# loader: custom_schema_loader.php
# Customize your schema lookup paths
  paths:
    - tests
#  cache:
#    class: LazyRecord\Cache\Memcache
#    servers:
#      - { host: localhost, port: 11211 }
data_sources:
  default:
    dsn: 'sqlite:testing.sqlite3'
#     dsn: 'sqlite::memory:'
    user: 
    pass: 
  pgsql:
    dsn: 'pgsql:host=localhost;dbname=testing'
    user: postgres
  mysql:
    dsn: 'mysql:host=localhost;dbname=testing'
    user: testing
#    slave:
#      dsn: 'mysql:host=localhost;dbname=test'
#      user: root
#      pass: 123123
