---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: 1
#  Customize your schema class loader
#
#  loader: custom_schema_loader.php

#  Customize your schema paths
  paths:
    - tests/schema
cache:
  class: LazyRecord\Cache\Memcache
  servers:
    - { host: localhost, port: 11211 }
data_sources:
  default:
    dsn: 'sqlite:tests.db'
    user: 
    pass: 
#    slave:
#      dsn: 'mysql:host=localhost;dbname=test'
#      user: root
#      pass: 123123
