---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: 1
# Customize your schema class loader
# loader: custom_schema_loader.php
# Customize your schema lookup paths
  paths:
    - tests
#  cache:
#    class: LazyRecord\Cache\Memcache
#    servers:
#      - { host: localhost, port: 11211 }
data_source:
  default: sqlite
  nodes:
    sqlite:
      dsn: 'sqlite:testing.sqlite3'
      # dsn: 'sqlite::memory:'
    pgsql:
      dsn: 'pgsql:host=localhost;dbname=testing'
      user: postgres
    mysql:
      dsn: 'mysql:host=localhost;dbname=testing'
      user: testing
