---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: 1
  paths:
    - tests
data_source:
  default: sqlite
  nodes:
    sqlite:
      dsn: 'sqlite:testing.sqlite3'
      driver: sqlite
      user: null
      pass: null
      query_options: {  }
      connection_options: {  }
    pgsql:
      dsn: 'pgsql:host=localhost;dbname=testing'
      user: postgres
      driver: pgsql
      pass: null
      query_options: {  }
      connection_options: {  }
    mysql:
      dsn: 'mysql:host=localhost;dbname=testing'
      user: testing
      driver: mysql
      pass: null
      query_options: {  }
      connection_options: { 1002: 'SET NAMES utf8' }
