---
bootstrap:
  - tests/bootstrap.php
schema:
#  Customize your schema class loader
#
#  loader: custom_schema_loader.php

#  Customize your schema paths
#  paths:
#    - tests/schema
data_sources:
  default:
    dsn: 'sqlite::memory:'
    user: 
    pass: 
#    slave:
#      dsn: 'mysql:host=localhost;dbname=test'
#      user: root
#      pass: 123123
