---
bootstrap:
  - bootstrap.php
schema:
#  Customize your schema paths
  paths:
    - src/
data_source:
  default: master
  nodes:
    master:
      driver: mysql
      database: todos
      user: root
      pass: 123123
    # slave:
    #   dsn: 'mysql:host=localhost;dbname=test'
    #   user: root
    #  pass: 123123
